"""
S.T.E.W Document Generator — REAL binary file generation.
Supports: PDF, DOCX, XLSX, PPTX, HTML
All files returned as base64-encoded strings.
"""
import base64
import io
import json
import logging
from datetime import datetime
from typing import Any, Optional

from fastapi import HTTPException

logger = logging.getLogger(__name__)


def _to_base64(buf: io.BytesIO) -> str:
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


# ── PDF ───────────────────────────────────────────────────────────────────────

def generate_pdf(content: str, title: str = "Document") -> dict:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
            title=title,
            author="S.T.E.W Agent",
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Title"],
            fontSize=18,
            spaceAfter=12,
            alignment=TA_CENTER,
        )
        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["Normal"],
            fontSize=11,
            leading=16,
            spaceAfter=8,
        )

        story = []
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.5 * cm))

        # Parse content — split by newline, detect headings
        for line in content.split("\n"):
            stripped = line.strip()
            if not stripped:
                story.append(Spacer(1, 0.3 * cm))
            elif stripped.startswith("## "):
                clean_h = stripped[3:].replace("**", "").replace("*", "")
                story.append(Paragraph(clean_h, styles["Heading2"]))
            elif stripped.startswith("# "):
                clean_h = stripped[2:].replace("**", "").replace("*", "")
                story.append(Paragraph(clean_h, styles["Heading1"]))
            elif stripped.startswith("- ") or stripped.startswith("* ") or stripped.startswith("• "):
                bullet_text = stripped.lstrip("-*• ").replace("**", "").replace("*", "")
                story.append(Paragraph(f"• {bullet_text}", body_style))
            else:
                # Strip **bold** and *italic* markers, escape HTML chars
                safe = stripped.replace("**", "").replace("*", "")
                safe = safe.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(safe, body_style))

        # Footer with timestamp
        story.append(Spacer(1, 1 * cm))
        footer_style = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
                                      textColor=colors.grey, alignment=TA_CENTER)
        story.append(Paragraph(
            f"Generated by S.T.E.W Agent • {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            footer_style,
        ))

        doc.build(story)
        filename = f"{title.replace(' ', '_')}_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}.pdf"
        return {
            "file": _to_base64(buf),
            "filename": filename,
            "mime_type": "application/pdf",
            "success": True,
        }
    except ImportError:
        raise HTTPException(500, "reportlab not installed — add it to requirements.txt")
    except Exception as e:
        logger.error(f"PDF generation error: {e}")
        raise HTTPException(500, f"PDF generation failed: {e}")


# ── DOCX ──────────────────────────────────────────────────────────────────────

def generate_docx(content: str, title: str = "Document") -> dict:
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Document title
        title_para = doc.add_heading(title, level=0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()  # spacer

        for line in content.split("\n"):
            stripped = line.strip()
            if not stripped:
                doc.add_paragraph()
            elif stripped.startswith("## "):
                doc.add_heading(stripped[3:].replace("**", "").replace("*", ""), level=2)
            elif stripped.startswith("# "):
                doc.add_heading(stripped[2:].replace("**", "").replace("*", ""), level=1)
            elif stripped.startswith("### "):
                doc.add_heading(stripped[4:].replace("**", "").replace("*", ""), level=3)
            elif stripped.startswith("- ") or stripped.startswith("* ") or stripped.startswith("• "):
                clean_bullet = stripped.lstrip("-*• ").replace("**", "").replace("*", "")
                doc.add_paragraph(clean_bullet, style="List Bullet")
            elif stripped.startswith("1. ") or (len(stripped) > 2 and stripped[0].isdigit() and stripped[1] == "."):
                doc.add_paragraph(stripped, style="List Number")
            else:
                doc.add_paragraph(stripped.replace("**", "").replace("*", ""))

        # Footer paragraph
        footer = doc.add_paragraph()
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer.add_run(
            f"Generated by S.T.E.W Agent • {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
        )
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        buf = io.BytesIO()
        doc.save(buf)
        filename = f"{title.replace(' ', '_')}_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}.docx"
        return {
            "file": _to_base64(buf),
            "filename": filename,
            "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "success": True,
        }
    except ImportError:
        raise HTTPException(500, "python-docx not installed")
    except Exception as e:
        logger.error(f"DOCX generation error: {e}")
        raise HTTPException(500, f"DOCX generation failed: {e}")


# ── XLSX ──────────────────────────────────────────────────────────────────────

def generate_xlsx(
    data: list[dict],
    sheet_name: str = "Sheet1",
    title: str = "Spreadsheet",
) -> dict:
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = sheet_name[:31]  # Excel sheet name limit

        if not data:
            data = [{"No data": "provided"}]

        headers = list(data[0].keys())

        # Header row styling
        header_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True, size=11)
        border = Border(
            left=Side(style="thin"),
            right=Side(style="thin"),
            top=Side(style="thin"),
            bottom=Side(style="thin"),
        )

        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_idx, value=header)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center", vertical="center")
            cell.border = border

        # Data rows
        alt_fill = PatternFill(start_color="EFF6FF", end_color="EFF6FF", fill_type="solid")
        for row_idx, row in enumerate(data, 2):
            for col_idx, header in enumerate(headers, 1):
                cell = ws.cell(row=row_idx, column=col_idx, value=row.get(header, ""))
                cell.border = border
                if row_idx % 2 == 0:
                    cell.fill = alt_fill

        # Auto-fit columns
        for col_idx, header in enumerate(headers, 1):
            max_len = max(
                len(str(header)),
                *[len(str(row.get(header, ""))) for row in data],
            )
            ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 4, 50)

        ws.freeze_panes = "A2"

        buf = io.BytesIO()
        wb.save(buf)
        filename = f"{title.replace(' ', '_')}_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}.xlsx"
        return {
            "file": _to_base64(buf),
            "filename": filename,
            "mime_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "success": True,
        }
    except ImportError:
        raise HTTPException(500, "openpyxl not installed")
    except Exception as e:
        logger.error(f"XLSX generation error: {e}")
        raise HTTPException(500, f"XLSX generation failed: {e}")


# ── PPTX ──────────────────────────────────────────────────────────────────────

def generate_pptx(slides: list[dict], title: str = "Presentation") -> dict:
    """Generate a clean, professional PPTX with custom dark theme slides."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt, Emu
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
        from pptx.oxml.ns import qn

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        # Color palette — clean dark theme
        BG_DARK = RGBColor(0x0F, 0x17, 0x2A)      # deep navy
        BG_CARD = RGBColor(0x1B, 0x25, 0x3B)      # slightly lighter
        ACCENT = RGBColor(0xF5, 0x9E, 0x0B)       # amber gold
        ACCENT_LIGHT = RGBColor(0xFD, 0xD8, 0x6E) # light gold
        WHITE = RGBColor(0xFF, 0xFF, 0xFF)
        LIGHT = RGBColor(0xCB, 0xD5, 0xE1)
        MUTED = RGBColor(0x94, 0xA3, 0xB8)
        DIVIDER = RGBColor(0x33, 0x3D, 0x52)

        BLANK = prs.slide_layouts[6]  # blank layout for full control

        def _add_bg(slide, color):
            bg = slide.background
            fill = bg.fill
            fill.solid()
            fill.fore_color.rgb = color

        def _add_textbox(slide, left, top, width, height, text, font_size,
                         color, bold=False, align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP):
            txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
            tf = txBox.text_frame
            tf.word_wrap = True
            tf.vertical_anchor = anchor
            tf.auto_size = None
            para = tf.paragraphs[0]
            para.text = text
            para.alignment = align
            run = para.runs[0] if para.runs else para.add_run()
            run.font.size = Pt(font_size)
            run.font.color.rgb = color
            run.font.bold = bold
            run.font.name = "Segoe UI"
            return tf

        def _add_bullets(slide, left, top, width, height, bullets, font_size=16, color=LIGHT):
            txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
            tf = txBox.text_frame
            tf.word_wrap = True
            for i, bullet in enumerate(bullets):
                if i == 0:
                    para = tf.paragraphs[0]
                else:
                    para = tf.add_paragraph()
                # Clean the bullet text
                clean = bullet.strip().lstrip("-").lstrip("•").strip()
                para.text = clean
                para.space_after = Pt(10)
                para.space_before = Pt(4)
                para.level = 0
                run = para.runs[0] if para.runs else para.add_run()
                run.font.size = Pt(font_size)
                run.font.color.rgb = color
                run.font.name = "Segoe UI"
            return tf

        def _add_accent_bar(slide, left, top, width=0.08, height=0.5):
            """Add a small gold accent bar."""
            from pptx.shapes.connector import Connector
            shape = slide.shapes.add_shape(
                1,  # MSO_SHAPE.RECTANGLE
                Inches(left), Inches(top), Inches(width), Inches(height)
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = ACCENT
            shape.line.fill.background()
            return shape

        for i, slide_data in enumerate(slides):
            slide_title = slide_data.get("title", f"Slide {i+1}")
            slide_content = slide_data.get("content", "")
            slide = prs.slides.add_slide(BLANK)
            _add_bg(slide, BG_DARK)

            if i == 0:
                # ── TITLE SLIDE ──
                # Gold accent bar at top
                _add_accent_bar(slide, 1.0, 2.8, width=2.5, height=0.06)
                # Main title
                _add_textbox(slide, 1.0, 3.0, 11.3, 1.5, slide_title,
                            font_size=44, color=WHITE, bold=True, align=PP_ALIGN.LEFT)
                # Subtitle (first bullet or topic)
                subtitle = slide_content.split("\n")[0].strip().lstrip("-").lstrip("•").strip() if slide_content else title
                if subtitle == slide_title:
                    subtitle = title
                _add_textbox(slide, 1.0, 4.5, 11.3, 0.8, subtitle,
                            font_size=20, color=ACCENT_LIGHT, bold=False, align=PP_ALIGN.LEFT)
                # Footer
                _add_textbox(slide, 1.0, 6.5, 11.3, 0.5,
                            "Generated by S.T.E.W Agent",
                            font_size=11, color=MUTED, align=PP_ALIGN.LEFT)
            else:
                # ── CONTENT SLIDE ──
                # Gold accent bar next to title
                _add_accent_bar(slide, 0.8, 0.7, width=0.08, height=0.6)
                # Title
                _add_textbox(slide, 1.1, 0.6, 11.0, 0.9, slide_title,
                            font_size=32, color=WHITE, bold=True, align=PP_ALIGN.LEFT)
                # Divider line
                divider = slide.shapes.add_shape(1, Inches(1.1), Inches(1.55), Inches(11.0), Inches(0.02))
                divider.fill.solid()
                divider.fill.fore_color.rgb = DIVIDER
                divider.line.fill.background()

                # Parse content into bullets
                bullets = []
                for line in slide_content.split("\n"):
                    clean = line.strip()
                    if clean:
                        bullets.append(clean)

                if bullets:
                    _add_bullets(slide, 1.3, 2.0, 10.8, 4.8, bullets, font_size=18, color=LIGHT)

        buf = io.BytesIO()
        prs.save(buf)
        clean_title = title.replace(" ", "_").replace("/", "_")[:40]
        filename = f"{clean_title}_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}.pptx"
        return {
            "file": _to_base64(buf),
            "filename": filename,
            "mime_type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "success": True,
        }
    except ImportError:
        raise HTTPException(500, "python-pptx not installed")
    except Exception as e:
        logger.error(f"PPTX generation error: {e}")
        raise HTTPException(500, f"PPTX generation failed: {e}")


# ── HTML ──────────────────────────────────────────────────────────────────────

def generate_html(content: str, title: str = "Report") -> dict:
    import html as html_module

    # Convert markdown-ish content to HTML
    lines = content.split("\n")
    body_html = []
    in_ul = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_ul:
                body_html.append("</ul>")
                in_ul = False
            body_html.append("<br>")
        elif stripped.startswith("## "):
            if in_ul:
                body_html.append("</ul>")
                in_ul = False
            body_html.append(f"<h2>{html_module.escape(stripped[3:])}</h2>")
        elif stripped.startswith("# "):
            if in_ul:
                body_html.append("</ul>")
                in_ul = False
            body_html.append(f"<h1>{html_module.escape(stripped[2:])}</h1>")
        elif stripped.startswith("### "):
            if in_ul:
                body_html.append("</ul>")
                in_ul = False
            body_html.append(f"<h3>{html_module.escape(stripped[4:])}</h3>")
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_ul:
                body_html.append("<ul>")
                in_ul = True
            body_html.append(f"<li>{html_module.escape(stripped[2:])}</li>")
        else:
            if in_ul:
                body_html.append("</ul>")
                in_ul = False
            body_html.append(f"<p>{html_module.escape(stripped)}</p>")

    if in_ul:
        body_html.append("</ul>")

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{html_module.escape(title)}</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
      background: #0f172a;
      color: #e2e8f0;
      line-height: 1.7;
      padding: 2rem;
    }}
    .container {{ max-width: 900px; margin: 0 auto; }}
    header {{
      background: linear-gradient(135deg, #1e293b, #0f172a);
      border-left: 4px solid #38bdf8;
      padding: 1.5rem 2rem;
      margin-bottom: 2rem;
      border-radius: 0 8px 8px 0;
    }}
    header h1 {{ color: #38bdf8; font-size: 2rem; }}
    header small {{ color: #94a3b8; font-size: 0.85rem; }}
    .content {{ background: #1e293b; padding: 2rem; border-radius: 8px; }}
    h1, h2, h3 {{ color: #38bdf8; margin: 1.5rem 0 0.75rem; }}
    h1 {{ font-size: 1.8rem; }}
    h2 {{ font-size: 1.4rem; border-bottom: 1px solid #334155; padding-bottom: 0.4rem; }}
    h3 {{ font-size: 1.1rem; color: #7dd3fc; }}
    p {{ margin-bottom: 0.8rem; color: #cbd5e1; }}
    ul {{ padding-left: 1.5rem; margin-bottom: 0.8rem; }}
    li {{ margin-bottom: 0.4rem; color: #cbd5e1; }}
    footer {{
      text-align: center;
      margin-top: 2rem;
      color: #64748b;
      font-size: 0.8rem;
    }}
    @media (max-width: 600px) {{ body {{ padding: 1rem; }} }}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>{html_module.escape(title)}</h1>
      <small>Generated by S.T.E.W Agent • {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</small>
    </header>
    <div class="content">
      {''.join(body_html)}
    </div>
    <footer>S.T.E.W — Structured Task Execution Workflow</footer>
  </div>
</body>
</html>"""

    buf = io.BytesIO(html_content.encode("utf-8"))
    filename = f"{title.replace(' ', '_')}_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}.html"
    return {
        "file": _to_base64(buf),
        "filename": filename,
        "mime_type": "text/html",
        "success": True,
    }
